### ISSUE TITLE
No Windows build documentation?

### ISSUE THREAD

**Issue by drsoops123** [uuosio/UUOSKit#1]
There was a recent fix (post the released 0.8.3 version) that I need to use.
I was able, after a bit of elbow grease, to build and install from the tip on Ubuntu. The problem is that I have no way of doing the same thing for a Windows distribution.
There is a build_win64.md file which has the most cryptic instructions ever, yet I see that there is a win wheel file for the most recent release. Can someone explain how to build from source for a windows 10 machine?

**Comment by ghost** [comment]
For compiling on Windows platform, please refer to the following link:

https://github.com/learnforpractice/pyeoskit#installing-prerequirementswindows <https://github.com/learnforpractice/pyeoskit#installing-prerequirementswindows>

**Comment by ghost** [comment]
Before the meeting, here is something you should know.在见证会举行前，你需要了解的事。Pre Meeting Checklist:https://www.notion.so/Pre-Meeting-Checklist-b4c999dbc4ad4f08a4955727f83667651、Read the Eden Peace Treaty. Ensure you understand and agree with it.       https://www.notion.so/5b15633ca09c4c6495a5b60f7bc92db2     请务必阅读EDEN和平条约，并确保你理解且赞成。2、Set up your profile on Eden     完善你Eden上的个人资料     Login to Eden and setup your profile. https://genesis.eden.eoscommunity.org/induction     登录此链接完善资料3、Prepare Zoom Call     准备Zoom会议    ① Install ： https://zoom.us/download#client_4meeting        安装Zoom    ② Change your background image in Zoom with the Eden Image        将Zoom的背景设置为Eden指定图片    ③ Check your audio, video        测试你的音频与视频效果    ④ Display name to your Name and Family name（Match the Proflie）        将显示名称设置为你的实际姓名（与profile匹配）Notice：1、When an invitee is recorded, please mute your mic and hide your video     在录制他人的入职视频时，请注意静音并隐藏你的视频画面2、This induction process must be completed within 7 days.      此入职流程必须在7天内完成Feel free to ask if you have any concerns.若有任何不解之处，欢迎随时询问。
