### ISSUE TITLE
what's the difference between pyeoskit and uuoskit?

### ISSUE THREAD

**Issue by encoderlee** [uuosio/UUOSKit#2]
what's the difference between pyeoskit and uuoskit?
[https://github.com/learnforpractice/pyeoskit](https://github.com/learnforpractice/pyeoskit)
[https://github.com/uuosio/UUOSKit](https://github.com/uuosio/UUOSKit)

**Comment by ghost** [comment]
UUOSKit is a fork of pyeoskit. Currently, `pyeoskit` is more active in development.
